#pragma once

#define EXTI_PORTA_IRQHANDLER 3
#define EXTI_PORTC_IRQHANDLER 5
#define EXTI_PORTD_IRQHANDLER 6
#define EXTI_PORTE_IRQHANDLER 7
#define TIM1_UPD_OVF_TRG_BRK_IRQHANDLER 11
#define TIM2_UPD_OVF_BRK_IRQHANDLER 13
#define ADC1_IRQHANDLER 22
#define UART2_IRQHANDLER 21
